---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    volumes:
      - /home/user/homer/assets:/www/assets
    ports:
      - 8081:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
